Copyright **`(c)`** 2024 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free under certain conditions — see the [`license`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [ ]:
from collections import namedtuple
from random import choice
from tqdm.auto import tqdm
import numpy as np

In [ ]:
def available_actions(state: np.ndarray) -> list['Action']:
    x, y = [int(_[0]) for _ in np.where(state == 0)]
    actions = list()
    if x > 0:
        actions.append(action((x, y), (x - 1, y)))
    if x < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x + 1, y)))
    if y > 0:
        actions.append(action((x, y), (x, y - 1)))
    if y < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x, y + 1)))
    return actions



def do_action(state: np.ndarray, action: 'Action') -> np.ndarray:
    new_state = state.copy()
    new_state[action.pos1], new_state[action.pos2] = new_state[action.pos2], new_state[action.pos1]
    return new_state

In [ ]:
def calc_manhattan(state):
  tot_dist = 0
  for i in range(len(state)):
    for j in range(len(state[i])):
      if state[i][j]==0:
        state[i][j]=len(state[i])**2
        x=(state[i][j]-1)//len(state[i])
        y=(state[i][j]-1)%len(state[i])
        tot_dist+=abs(x-i)+abs(y-j)
        state[i][j]=0
      else:
        x=(state[i][j]-1)//len(state[i])
        y=(state[i][j]-1)%len(state[i])
        tot_dist+=abs(x-i)+abs(y-j)
  return tot_dist

In [ ]:
PUZZLE_DIM = 5
action = namedtuple('Action', ['pos1', 'pos2'])

In [ ]:
RANDOMIZE_STEPS = 80
state = np.array([i for i in range(1, PUZZLE_DIM**2)] + [0]).reshape((PUZZLE_DIM, PUZZLE_DIM))
for r in tqdm(range(RANDOMIZE_STEPS), desc='Randomizing'):
    state = do_action(state, choice(available_actions(state)))
print(state)

Randomizing:   0%|          | 0/80 [00:00<?, ?it/s]

[[ 1  2  9  4 10]
 [ 6  7  3 14 13]
 [16 11  8  5 15]
 [12 22 17 19 20]
 [ 0 21 18 23 24]]


In [ ]:
ideal_state = np.array([i for i in range(1, PUZZLE_DIM**2)] + [0]).reshape((PUZZLE_DIM, PUZZLE_DIM))
states_list=[[state,0,calc_manhattan(state)]]
state = states_list[0]

In [ ]:
print(states_list)

[[array([[ 1,  2,  9,  4, 10],
       [ 6,  7,  3, 14, 13],
       [16, 11,  8,  5, 15],
       [12, 22, 17, 19, 20],
       [ 0, 21, 18, 23, 24]]), 0, 26]]


In [ ]:
y=0
while not np.array_equal(state[0], ideal_state):
  for i in available_actions(state[0]):
    new_state = do_action(state[0], i)
    y+=1
    is_in=any(np.array_equal(new_state, state_info[0]) for state_info in states_list)
    if not is_in:
      cost=calc_manhattan(new_state)+state[1]+1
      states_list.append([new_state,state[1]+1,cost])
  states_list.pop(0)
  states_list.sort(key=lambda x: x[2])
  state = states_list[0]
print("Solution:",state[0])
print("Number of steps to solve:", state[1])
print("Total number of steps:", y)

Solution: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24  0]]
Number of steps to solve: 32
Total number of steps: 84218
